config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :students
  resources :courses do
    member do
      get 'enroll'
      post 'enroll_student'
    end
    member do
    delete 'remove_student/:student_id', to: 'courses#remove_student', as: :remove_student
  end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :course_students
	has_many :students, through: :course_students

	validates :name, presence: true, length: { minimum: 5 }
	validates :start_date, presence: true
	validates :end_date, presence: true

	before_validation do 
		puts "Message before validations"
	end
	
	before_save :course_save_message


	def course_save_message
		puts "This message is displayed before saving the course"
	end
end

app/models/course_student.rb
class CourseStudent < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :course_students
	has_many :courses, through: :course_students
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
    @student_names = @course.students.pluck(:name)
  end

  def enroll
    @course_to_enroll = Course.find(params[:id])
    @available_students = Student.where.not(id: @course_to_enroll.students.pluck(:id))
  end

  def enroll_student
    @course_to_enroll = Course.find(params[:id])
    @enrolled_student  = Student.find(params[:student_id])

    if @course_to_enroll.students.include?(@enrolled_student)
      flash[:alert] = "Stduent is already enrolled in this course"
    else
      @course_to_enroll.students << @enrolled_student
      flash[:notice] = "Student enrolled successfully"
    end
    redirect_to courses_path
  end

def remove_student
  @course = Course.find(params[:id])
  @student_to_remove = @course.students.find(params[:student_id])

  if @course.students.destroy(@student_to_remove)
    flash[:notice] = "Student removed from the course successfully."
  else
    flash[:alert] = "Failed to remove student from the course."
  end
  redirect_to course_path(@course)
end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(params.require(:course).permit(:name, :start_date, :end_date))
    if @course.save
    flash[:notice] = "Course is successfully created."
    redirect_to @course
    else 
      render 'new'
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    flash[:notice] = "Course removed successfully."
    redirect_to courses_path
  end

  def edit
     @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update(params.require(:course).permit(:name, :start_date, :end_date))
      flash[:notice] = "Course details updated successfully."
      redirect_to @course
    else
      render :edit
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
    @courses_name = @student.courses.pluck(:name)
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(params.require(:student).permit(:name, :age, :email))
    if @student.save
    flash[:notice] = "Student is successfully created."
    redirect_to @student
    else 
      render 'new'
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    flash[:notice] = "Student removed successfully."
    redirect_to students_path
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(params.require(:student).permit(:name, :age, :email))
      flash[:notice] = "Student details updated successfully."
      redirect_to @student
    else
      render :edit
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/edit.html.erb
<h1>Edit Course Details</h1>
<%= form_with model: @course do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :start_date %><br>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date %><br>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Cancel & Return to Course List' , courses_path %>

app/views/courses/enroll.html.erb
<h2> Enroll Student in <%= @course_to_enroll.name %> </h2>

<%= form_for @course_to_enroll, url: enroll_student_course_path(@course_to_enroll), method: :post do |f| %>
	<%= f.label :student_id, "Select Student to Enroll:" %>
    <%= select_tag 'student_id', options_from_collection_for_select(@available_students, 'id', 'name'), prompt: "Select Student" %>
    <%= f.submit "Enroll Student", class: "btn btn-primary" %>
<% end %>
<%= link_to 'Back to Course List Page' , courses_path %>

app/views/courses/index.html.erb
<h1> Course List Page</h1>
<table bgcolor="white", border="2">
	<thead>
		<th>Name</th>
		<th>Start Date</th>
		<th>End Date</th>
		<th colspan="4"> Actions</th>
	</thead>
	<tbody>
		
  	<% @courses.each do |course| %>
		<tr>
		<td><%= course.name %></td>
		<td><%= course.start_date %></td>
		<td><%= course.end_date %></td>
		<td><%=  link_to 'Show' ,course_path(course)%></td>
		<td><%=  link_to 'Delete',  course_path(course), method: :delete, data: {confirm: "Are You Sure?"}%></td>
		<td><%=  link_to 'Edit', edit_course_path(course) %></td>
		<td><%=  link_to 'Enroll', enroll_course_path(course) %></td>
	</tr>
	<% end %>
	</tbody>
</table>
<%= link_to 'Create New Course', new_course_path %><br>
<%= link_to 'Back to main menu', root_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= form_with model: @course do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>

    <% @course.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :start_date %><br>
    <%= form.date_field :start_date %>
    <% @course.errors.full_messages_for(:start_date).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :end_date %><br>
    <%= form.date_field :end_date %>
    <% @course.errors.full_messages_for(:end_date).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back to Course List' , courses_path %>

app/views/courses/show.html.erb
<h1> Course Details</h1>
  <p><strong>Name:</strong><%= @course.name %> </p>
  <p><strong>Start Date:</strong><%= @course.start_date %></p>
   <p><strong>End Date:</strong><%= @course.end_date %></p>

  <h2> Enrolled Students </h2>
<ol>
  <% @course.students.each do |student| %>
    <li>
      <%= student.name %> -
      <%= link_to 'Remove', remove_student_course_path(@course, student), method: :delete, data: { confirm: 'Are you sure to remove student?' } %>
    </li>
  <% end %>
</ol>
<%= link_to 'Back to Course List' , courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentCourse</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name,msg| %>
    <%= msg %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1>Edit Student Details</h1>
<%= form_with model: @student do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age %><br>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Cancel & Return to Student List' , students_path %>

app/views/students/index.html.erb
<h1> Student List Page</h1>
<table bgcolor="white", border="2">
	<thead>
		<th>Student</th>
		<th>Age</th>
		<th>Email</th>
		<th colspan="5"> Actions</th>
	</thead>
	<tbody>
		
  	<% @students.each do |student| %>
		<tr>
		<td><%= student.name %></td>
		<td><%= student.age %></td>
		<td><%= student.email %></td>
		<td><%=  link_to 'Show' ,student_path(student)%></td>
		<td><%=  link_to 'Delete',  student_path(student), method: :delete, data: {confirm: "Are You Sure?"}%></td>
		<td><%=  link_to 'Edit', edit_student_path(student) %></td>
	</tr>
	<% end %>
	</tbody>
</table>
<%= link_to 'Create New Student', new_student_path %><br>
<%= link_to 'Back to main menu',  root_path %>

app/views/students/new.html.erb
<h1>Create Student</h1>
<%= form_with model: @student do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age %><br>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Cancel & Return to Student List' , students_path %>

app/views/students/show.html.erb
<h1> Student Details</h1>
  <p><strong>Name:</strong><%= @student.name %> </p>
  <p><strong>Age:</strong><%= @student.age %></p>
  <p><strong>Email:</strong><%= @student.email %></p>

  <p><strong> Enrolled Courses:</p></strong>
  <ol>
    <% @courses_name.each do |course_name| %>
    <li><%= course_name%></li>
    <% end %>
  </ol>

  <%= link_to 'Back to Student List Page' , students_path %>

app/views/welcome/index.html.erb
<h1> Welcome, To Student Course Enrollment Application </h1>
<p> Students List:<strong><%= link_to 'Student', students_path %></strong></p>
<p> Courses List:<strong><%= link_to 'Course', courses_path  %></strong></p>